events {}

http {
  server {
    listen 80;

    location /auth/ {
      proxy_pass http://auth-service:3000/;
    }

    location /parking/ {
      proxy_pass http://parking-service:3000/;
    }

    location /bookings/ {
      proxy_pass http://booking-service:3000/;
    }

    location /payments/ {
      proxy_pass http://payment-service:3000/;
    }

    location /reports/ {
      proxy_pass http://report-service:3000/;
    }

    location /notifications/ {
      proxy_pass http://notification-service:3000/;
    }
  }
}
