version: '3.8'

services:
  load-balancer:
    build:
      context: ./load-balancer
    ports:
      - "8443:443"
    depends_on:
      api-gateway:
        condition: service_started

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:80"
    depends_on:
      authentication-service:
        condition: service_started
      user-management-service:
        condition: service_started
      parking-service:
        condition: service_started
      device-service:
        condition: service_started
      booking-service:
        condition: service_started
      payment-service:
        condition: service_started
      report-service:
        condition: service_started
      notification-service:
        condition: service_started
      frontend:
        condition: service_started

  authentication-service:
    build:
      context: ./authentication-service
    ports:
      - "3001:3000"
    depends_on:
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/authdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/authdb

  user-management-service:
    build:
      context: ./user-management-service
    ports:
      - "3008:3000"
    depends_on:
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/userdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/userdb

  parking-service:
    build:
      context: ./parking-service
    ports:
      - "3002:3000"
    depends_on:
      parking-db-primary:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@parking-db-primary:5432/parkingdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@parking-db-primary:5432/parkingdb
      - RABBITMQ_URL=amqp://rabbitmq:5672

  device-service:
    build:
      context: ./device-service
    ports:
      - "3007:3000"
      - "9000:9000"
      - "554:554"
    depends_on:
      parking-service:
        condition: service_started
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - PARKING_SERVICE_URL=http://parking-service:3000
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/devicedb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/devicedb
      - RABBITMQ_URL=amqp://rabbitmq:5672

  booking-db-primary:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=bookingdb
    volumes:
      - ./booking-service/pg-primary-data:/bitnami/postgresql
      - ./pg-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  booking-db-replica:
    image: bitnami/postgresql:latest
    depends_on:
      booking-db-primary:
        condition: service_healthy
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=booking-db-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
    volumes:
      - ./booking-service/pg-replica-data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-db-primary:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=paymentdb
    volumes:
      - ./payment-service/pg-primary-data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  parking-db-primary:
    image: bitnami/postgresql:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=parkingdb
    volumes:
      - ./parking-service/pg-primary-data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d parkingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  booking-service:
    build:
      context: ./booking-service
    ports:
      - "3003:3000"
    depends_on:
      parking-service:
        condition: service_started
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/bookingdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/bookingdb
      - RABBITMQ_URL=amqp://rabbitmq:5672

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3004:3000"
    depends_on:
      booking-service:
        condition: service_started
      payment-db-primary:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@payment-db-primary:5432/paymentdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@payment-db-primary:5432/paymentdb
      - USER_MANAGEMENT_SERVICE_URL=http://user-management-service:3000
      - BOOKING_SERVICE_URL=http://booking-service:3000
      - NOTIFICATION_SERVICE_URL=http://notification-service:3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./payment-service/.env

  report-service:
    build:
      context: ./report-service
    ports:
      - "3005:3000"
    depends_on:
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/reportdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/reportdb
      - RABBITMQ_URL=amqp://rabbitmq:5672

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3006:3000"
    depends_on:
      booking-db-primary:
        condition: service_healthy
      booking-db-replica:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - POSTGRES_PRIMARY_URL=postgres://myuser:mypassword@booking-db-primary:5432/notificationdb
      - POSTGRES_REPLICA_URL=postgres://myuser:mypassword@booking-db-replica:5432/notificationdb
      - RABBITMQ_URL=amqp://rabbitmq:5672
    env_file:
      - ./notification-service/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
